from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional

from security_agent.models.scan_result import ScanResult


@dataclass
class ReportMetadata:
    generated_at: str = field(default_factory=lambda: datetime.now().isoformat())
    report_format: str = "html"
    tool_version: str = "1.0.0"
    disclaimer: str = (
        "This report is generated by an automated security scanning tool. "
        "Findings should be verified by a qualified security professional. "
        "Only scan websites you own or have explicit written authorization to test."
    )


@dataclass
class Report:
    scan_result: ScanResult
    metadata: ReportMetadata = field(default_factory=ReportMetadata)
    executive_summary: str = ""
    ai_risk_assessment: str = ""
    attack_chains: list[dict] = field(default_factory=list)
    remediation_roadmap: list[dict] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "metadata": {
                "generated_at": self.metadata.generated_at,
                "report_format": self.metadata.report_format,
                "tool_version": self.metadata.tool_version,
                "disclaimer": self.metadata.disclaimer,
            },
            "scan_result": self.scan_result.to_dict(),
            "executive_summary": self.executive_summary,
            "ai_risk_assessment": self.ai_risk_assessment,
            "attack_chains": self.attack_chains,
            "remediation_roadmap": self.remediation_roadmap,
        }
